dataset_config:
  dataset_name: imagenet
  dataset_builder: imagenet
  save_dir: ../data
  val_samples: 1000
    
  preprocess:
    name: vision
    vision_transforms:
      transforms_train:
        - RandomResizedCrop
        - RandomHorizontalFlipImageOnly
        - ToTensor
        - RandomAugment
        - Normalise
      transforms_test:
        - Resize
        - ToTensor
        - Normalise
      # params must have the same name as 
      # transforms list above to ensure
      # parameters are loaded to the right 
      # transforms class
      params:
        RandomResizedCrop: 
          size: [224, 224] # height, width
        
        Resize: 
          size: [224, 224] # height, width

        ToTensor: null
        
        RandomAugment:
          augment_parameters:
            - 0.8
            - 1.2
            - 0.5
            - 2.0
            - 0.8
            - 1.2
          do_augmentation: True
        
        Normalise: 
          norm_type: imagenet


    