tokenizer_config: vqkd_encoder_base_decoder_3x768x12_clip

    n_embed: 8192
    embed_dim: 32
    decay: 0.99
    process_type: 'default'
    quantize_kmeans_init: True
    teacher_model_type: 'clip'
    decoder_out_dim: 512
    rec_loss_type: 'cosine'

image_encoder:
    patch_size: [16, 32]
    in_channels: 3
    embed_dim: 768
    depth: 12
    mlp_ratio: 4
    num_heads: 12

image_decoder:
    decoder_embed_dim: 512
    decoder_depth: 8
    decoder_num_heads: 16

image_loss_weightings:
    ssim: 0.85
    style: 40.0
    perc: 0.05
    gan: 0.7 
    l1: 1.0

discriminator:
    depth: 6
    conv_layer_type: 'default'
    feature_size_ndf: 512
    input_channels_nc: 3
    gan_arch_type: 'msg'


